# Generated by Django 4.0.6 on 2022-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheet',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='googlesheet',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='googlesheet',
            name='mail',
        ),
        migrations.AddField(
            model_name='googlesheet',
            name='bussines_type',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
