# Generated by Django 4.0.6 on 2022-07-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_remove_googlesheet_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheet',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
